
import java.io.IOException;
import java.net.SocketException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.FTPSClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() throws IOException {
        initComponents();
        setTitle("Delete Wizard");
        
         FTPSClient ftpClient = new FTPSClient(false);
   
         ftpClient.connect("ftp.p9.webhosting.yahoo.com", 21);
   boolean login = ftpClient.login("ankit.gajbhiye@ankitgajbhiye.com", "password");  
        System.out.println("vlaue of login"+ login);
   if (login) {  
    System.out.println("Connection established...");  
    //FTPFile[] files = ftpClient.listFiles("/upload/");
            
          
          //fos = new FileOutputStream("E:/abcd.txt"); 
          //System.out.println("abcd created");
           //boolean downld = ftpClient.retrieveFile("/upload/abc.txt",fos);
           ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
    ftpClient.enterLocalPassiveMode();
    ftpClient.setAutodetectUTF8(true);
    
    String s = null;
    DefaultListModel model = new DefaultListModel();
              FTPFile[]  ftpFiles = ftpClient.listFiles("/upload/");
                      for (FTPFile ftpFile : ftpFiles) {
                s = ftpFile.getName();
          
                                     
                
                           model.addElement(s);
            }
                      jList1.setModel(model);
                      

   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(394, 195, 160, 41);

        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(82, 117, 201, 240);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("File Deletion");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 607, 50);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 387, 95, 41);

        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(299, 387, 95, 41);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(564, 387, 95, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Select a file and click Delete");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 80, 190, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(60, 10, 590, 40);

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(40, 70, 650, 300);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Files on server:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 100, 110, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit\\Desktop\\361841347_640.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 720, 450);

        setSize(new java.awt.Dimension(736, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        String sd = null;
         FTPSClient ftpClient = new FTPSClient(false);
        
  try {  
   
 
      // Connect to host
      ftpClient.connect("ftp.p9.webhosting.yahoo.com", 21);
   boolean login = ftpClient.login("ankit.gajbhiye@ankitgajbhiye.com", "password");  
       
   
      if (login) {  
    System.out.println("Connection established...");  
    //FTPFile[] files = ftpClient.listFiles("/upload/");
       
    List s = jList1.getSelectedValuesList();
            
          String strarray;
          strarray = s.toString();
       
       int l = strarray.length();
       
        sd = strarray.substring(1, l-1);
     
        int selectedOption =   JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this file?","Choose", JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) {
                
                 
    boolean delete = ftpClient.deleteFile("/upload/"+sd);  
    if (delete) {  
     JOptionPane.showMessageDialog(this, "You hvae successfully Deleted " + "'" + sd + "'" + " from the server !!" );
    refresh();     
    } else {  
     JOptionPane.showMessageDialog(this, "Error in deleting file" );
    }  
  
    // logout the user, returned true if logout successfully  
    boolean logout = ftpClient.logout();  
    if (logout) {  
     System.out.println("Connection close...");  
    }  
   }
         else {
                Delete del = new Delete();
           
            del.setVisible(true);
             
           
             
            }
  
   

  }
     else {  
    System.out.println("Connection fail...");  
   }  
  
  }     catch (SocketException e) {  
            e.printStackTrace();  
  }      catch (IOException e) {  
            e.printStackTrace();  
  } 
  finally {  
   try {  
    ftpClient.disconnect();  
   } catch (IOException e) {  
    e.printStackTrace();  
   }  
  }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Logon l1 = new Logon();
       l1.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Selection sel = new Selection();
        sel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
public void refresh() throws IOException{
     FTPSClient ftpClient = new FTPSClient(false);
            ftpClient.connect("ftp.p9.webhosting.yahoo.com", 21);
   boolean login = ftpClient.login("ankit.gajbhiye@ankitgajbhiye.com", "password");  
       
   if (login) {  
    System.out.println("Connection established...");  
    //FTPFile[] files = ftpClient.listFiles("/upload/");
            
          
          //fos = new FileOutputStream("E:/abcd.txt"); 
          //System.out.println("abcd created");
           //boolean downld = ftpClient.retrieveFile("/upload/abc.txt",fos);
           ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
    ftpClient.enterLocalPassiveMode();
    ftpClient.setAutodetectUTF8(true);
    
    String s = null;
    DefaultListModel model = new DefaultListModel();
              FTPFile[]  ftpFiles = ftpClient.listFiles("/upload/");
                      for (FTPFile ftpFile : ftpFiles) {
                s = ftpFile.getName();
          
                                     
                
                           model.addElement(s);
            }
                      jList1.setModel(model);
                      

   }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Delete().setVisible(true);
                } catch (IOException ex) {
                    System.out.println("erroororor");
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
