
import java.awt.Color;
import java.awt.Desktop;
import java.beans.Statement;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.Socket;
import java.net.URI;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit
 */
public class Logon extends javax.swing.JFrame {

    
    /**
     * Creates new form Logon
     */
    

    @Override
    public void setTitle(String string) {
        super.setTitle("MADPILOTS Socket API"); //To change body of generated methods, choose Tools | Templates.
    }
    
    public Logon() {
        initComponents();
        setResizable(true);
        setTitle("MadPilots Socket");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        NewUser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        UserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserName.setText("User Name");
        UserName.setToolTipText("");
        getContentPane().add(UserName);
        UserName.setBounds(455, 107, 99, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(455, 135, 183, 29);

        Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Password.setText("Password");
        Password.setToolTipText("");
        getContentPane().add(Password);
        Password.setBounds(455, 179, 87, 22);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(455, 207, 183, 31);

        Login.setBackground(new java.awt.Color(0, 102, 0));
        Login.setText("Login");
        Login.setPreferredSize(new java.awt.Dimension(73, 23));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(455, 249, 89, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MADPILOTS SOCKET API");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 476, 44);

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 10, 650, 50);

        NewUser.setBackground(new java.awt.Color(0, 102, 0));
        NewUser.setText("Sign Up");
        NewUser.setMaximumSize(new java.awt.Dimension(57, 23));
        NewUser.setMinimumSize(new java.awt.Dimension(57, 23));
        NewUser.setPreferredSize(new java.awt.Dimension(57, 23));
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });
        getContentPane().add(NewUser);
        NewUser.setBounds(554, 249, 84, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Forgot Password?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(477, 297, 142, 32);

        jSeparator3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(430, 90, 240, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit\\Pictures\\lovely-linux-network-programming-centos-linux-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 450);

        setSize(new java.awt.Dimension(726, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

                   String user = jTextField1.getText();
             String Pass = new String(jPasswordField1.getPassword());
        
             
             
             if(user.equals("ankit") && Pass.equals("password"))
       {
//           
//           Upload up1 = new Upload();
//           Upload.jLabel2.setText("Hello " + this.jTextField1.getText() + "!");
//            up1.setVisible(true);
                        Selection sel = new Selection();
        //   Selection.jLabel2.setText("Hello " + this.jTextField1.getText() + "!");
            sel.setVisible(true);
           //Selection.jLabel2.setText("Hello " + this.jTextField1.getText() + "!");
           dispose();
           
       }
             else if(user.equals("admin") && Pass.equals("admin"))
       {
           
//           Upload up1 = new Upload();
//           Upload.jLabel2.setText("Hello " + this.jTextField1.getText() + "!");
//            up1.setVisible(true);
             Selection sel = new Selection();
           //Selection.jLabel2.setText("Hello " + this.jTextField1.getText() + "!");
            sel.setVisible(true);
           dispose();
           
           
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Invalid Username or password");
       }    
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
    
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        
    }//GEN-LAST:event_LoginKeyPressed

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
        String url = "http://ankitgajbhiye.com/phptest/insertdata.html";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(Logon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NewUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String url = "http://ankitgajbhiye.com/phptest/forgotpassword.php";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(Logon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton NewUser;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
