
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.FTPSClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit
 */
public class Upload1 extends javax.swing.JFrame {

    
    String  FilePath =null;
    /**
     * Creates new form Upload1
     */
    public Upload1() throws IOException {
        initComponents();
        setTitle("Upload Wizard");
        FTPSClient ftpClient = new FTPSClient(false);
        System.out.println("list update");
                  ftpClient.connect("ftp.p9.webhosting.yahoo.com", 21);
                  System.out.println("connn");
                  
   boolean login = ftpClient.login("password
localhost", "Firefoxqa1@");  
        System.out.println("co123");
        System.out.println("value of login" + login);
       
   if (login) {  
    System.out.println("Connection established...");  
    //FTPFile[] files = ftpClient.listFiles("/upload/");
            
          
          //fos = new FileOutputStream("E:/abcd.txt"); 
          //System.out.println("abcd created");
           //boolean downld = ftpClient.retrieveFile("/upload/abc.txt",fos);
           ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
    ftpClient.enterLocalPassiveMode();
    ftpClient.setAutodetectUTF8(true);
    
    String s;
    DefaultListModel model = new DefaultListModel();
              FTPFile[]  ftpFiles = ftpClient.listFiles("/upload/");
                      for (FTPFile ftpFile : ftpFiles) {
                s = ftpFile.getName();
                          System.out.println(s);
          
                 
                
                           model.addElement(s);
            }
                      jList1.setModel(model);
                      

   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textfield = new javax.swing.JTextField();
        Browse = new javax.swing.JButton();
        upload_file = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("File Upload ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 602, 60);
        getContentPane().add(textfield);
        textfield.setBounds(50, 180, 220, 30);

        Browse.setText("Browse");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        getContentPane().add(Browse);
        Browse.setBounds(300, 170, 95, 40);

        upload_file.setText("Upload");
        upload_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_fileActionPerformed(evt);
            }
        });
        getContentPane().add(upload_file);
        upload_file.setBounds(180, 260, 95, 41);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 400, 95, 41);

        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(320, 400, 95, 41);

        jButton5.setText("Exit");
        jButton5.setMaximumSize(new java.awt.Dimension(57, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(57, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(550, 400, 95, 41);

        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 120, 215, 250);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Files already on server");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 90, 215, 25);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(450, 80, 260, 310);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please select file to upload");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 110, 220, 40);

        jSeparator3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 100, 410, 270);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit\\Desktop\\361841347_640.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 720, 470);

        setSize(new java.awt.Dimension(736, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Logon L1 = new Logon();
           
            L1.setVisible(true);
             
           dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            Selection s1 = new Selection();
           
            s1.setVisible(true);
             
           dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void upload_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_fileActionPerformed


      
      String URLPath = "http://ankitgajbhiye.com/accept.php";
   
        
        HttpURLConnection conn = null;

        DataOutputStream dos = null;

        DataInputStream inStream = null;

        String lineEnd = "\r\n";

        String twoHyphens = "--";

        String boundary =  "*****";

        int bytesRead, bytesAvailable, bufferSize;

        byte[] buffer;

        int maxBufferSize = 1*1024*1024;

        try{

            FileInputStream fileInputStream = new FileInputStream(new File(FilePath));

            URL url = new URL(URLPath);

            conn = (HttpURLConnection) url.openConnection();

            conn.setDoInput(true);

            conn.setDoOutput(true);

            conn.setUseCaches(false);

            conn.setRequestMethod("POST");

            conn.setRequestProperty("Connection", "Keep-Alive");

            conn.setRequestProperty("Charset", "UTF-8");

            conn.setRequestProperty("Content-Type", "multipart/form-data;boundary=" + boundary);

            dos = new DataOutputStream( conn.getOutputStream() );

            dos.writeBytes(twoHyphens + boundary + lineEnd);

            dos.writeBytes("Content-Disposition: form-data; name=\"uploadfile\"; filename=\""  

                    + FilePath.substring(FilePath.lastIndexOf("/") + 1) + "\"" + lineEnd); 

            dos.writeBytes(lineEnd);

            bytesAvailable = fileInputStream.available();

            bufferSize = Math.min(bytesAvailable, maxBufferSize);

            buffer = new byte[bufferSize];

            // read file and write it into form...

            bytesRead = fileInputStream.read(buffer, 0, bufferSize);

         while (bytesRead > 0){

             dos.write(buffer, 0, bufferSize);

             bytesAvailable = fileInputStream.available();

             bufferSize = Math.min(bytesAvailable, maxBufferSize);

             bytesRead = fileInputStream.read(buffer, 0, bufferSize);

         }

         dos.writeBytes(lineEnd);

         dos.writeBytes(twoHyphens + boundary + twoHyphens + lineEnd);

         fileInputStream.close();

         dos.flush();

         dos.close();



       

       

        }catch (MalformedURLException ex){

            System.out.println("From ServletCom CLIENT REQUEST:"+ex);

        }catch (IOException ioe){

            System.out.println("From ServletCom CLIENT REQUEST:"+ioe);

        }

        try {

            inStream = new DataInputStream ( conn.getInputStream() );

            String str;

            while (( str = inStream.readLine()) != null){

                System.out.println("Server response is: " + str);

            }

            inStream.close();

        }catch (IOException ioex){

            System.out.println("From (ServerResponse): " + ioex);

      }

 
//       Upload1 up;
//        try {
//            up = new Upload1();
//            up.setVisible(true);
//        } catch (IOException ex) {
//            System.out.println("eoroeoroer");
//        }
       JOptionPane.showMessageDialog(this,"Congratulations! You have succesfully uploaded file on server!");
        try {
            refresh();
            
            //jLabel2.setText("Congratulations! You have succesfully uploaded file on server!");
        } catch (IOException ex) {
            System.out.println("refresh error");
        }

            
  

    }//GEN-LAST:event_upload_fileActionPerformed

    public void refresh() throws IOException{
        
            FTPSClient ftpClient = new FTPSClient(false);
   
         ftpClient.connect("ftp.password
localhost.net", 21);
   boolean login = ftpClient.login("password
localhost", "Firefoxqa1@");  
       
   if (login) {  
    System.out.println("Connection established...");  
    //FTPFile[] files = ftpClient.listFiles("/upload/");
            
          
          //fos = new FileOutputStream("E:/abcd.txt"); 
          //System.out.println("abcd created");
           //boolean downld = ftpClient.retrieveFile("/upload/abc.txt",fos);
           ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
    ftpClient.enterLocalPassiveMode();
    ftpClient.setAutodetectUTF8(true);
    
    
    String s = null;
    DefaultListModel model = new DefaultListModel();
              FTPFile[]  ftpFiles = ftpClient.listFiles("/upload/");
                      for (FTPFile ftpFile : ftpFiles) {
                s = ftpFile.getName();
          
                                     
                
                           model.addElement(s);
            }
                      jList1.setModel(model);
                      
   }

    }
    
    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
             
             
        JFileChooser chooser = new JFileChooser();
            chooser.setMultiSelectionEnabled(true);
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
             int result = chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = chooser.getSelectedFile();
            textfield.setText(file.getAbsolutePath());
            FilePath = file.getAbsolutePath();
         }        // TODO add your handling code here:

    }//GEN-LAST:event_BrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Upload1().setVisible(true);
                } catch (IOException ex) {
                    System.out.println("eroorrrrr");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField textfield;
    private javax.swing.JButton upload_file;
    // End of variables declaration//GEN-END:variables
}
